FROM python:3.8.10

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/streamer

CMD sleep 60 && faust -A consumer worker -l info
